[package]
name = "avm_rust"
version = "0.1.0"
authors = ["cledant <cledant@student.42.fr>"]

[dependencies]
avm_lib = { path = "./avm_lib" }

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
