[package]
name = "operand"
version = "0.1.0"
authors = ["cledant <cledant@student.42.fr>"]

[dependencies]
num = "0.2"
num-traits = "0.2.5"

[profile.dev]
opt-level = 3

[profile.release]
opt-level = 3
